name: lint and test

on: [push]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        run: pip install poetry==1.5.1

      - name: Install code
        run: poetry install

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run flake8 . --count --exit-zero --statistics

      - name: Check formatting with Black
        run: poetry run black . --check

      - name: Check import order with isort
        run: poetry run isort -c src

      - name: Test with pytest
        run: poetry run pytest -v --cov webapp
